/*
 * Why do we need this class?
 *
 * This filter ensures that every request has a Correlation ID. (A
 * Correlation ID is a unique identifier assigned to a request so it can
 * be tracked across multiple microservices.)
 *
 * If the client already sends a Correlation ID, this filter keeps it.
 * Otherwise, it generates a new one, adds it to the response, and makes
 * it available to the logging system throughout the request.
 *
 * Why we need it:
 * It allows developers to trace a single request across all
 * microservices, making debugging and troubleshooting much easier.
 */

/*
 * Important Variable:
 *
 * CONTEXT_KEY -> The key used to store the Correlation ID inside the
 * Reactor Context and MDC so it remains available during the entire
 * request processing.
 */

/*
 * Overall Flow:
 *
 * Client Sends Request
 *          |
 *          v
 * Check Correlation ID Header
 *          |
 *      Present?
 *      |
 *   Yes ----------> Use Existing ID
 *      |
 *     No
 *      |
 *      v
 * Generate New Correlation ID
 *          |
 *          v
 * Add ID to Response Header
 *          |
 *          v
 * Store ID in Reactor Context
 *          |
 *          v
 * Copy ID to MDC for Logging
 *          |
 *          v
 * Process Request
 *          |
 *          v
 * Remove ID from MDC
 */

/*
 * What are Correlation ID, Reactor Context, and MDC?
 *
 * Correlation ID -> A unique ID that identifies one complete request
 * across multiple microservices.
 *
 * Reactor Context -> A storage area used by reactive applications to carry
 * request-specific data safely across different threads.
 *
 * MDC (Mapped Diagnostic Context) -> A temporary logging storage that
 * automatically adds information like the Correlation ID to every log
 * message generated during the request.
 *
 * Reactor Context keeps the Correlation ID alive during asynchronous
 * processing, while MDC makes sure it appears in the application logs.
 */

/*
 * Example:
 *
 * Customer creates a payment.
 *
 * Correlation ID:
 * 3f8b8b9c-a12f-4f7d-b2d6-123456789abc
 *
 * API Gateway
 *      |
 *      v
 * Merchant Service
 *      |
 *      v
 * Token Vault
 *      |
 *      v
 * Payment Orchestrator
 *      |
 *      v
 * Acquiring Adapter
 *      |
 *      v
 * Settlement Service
 *
 * Every log generated by these services contains the same Correlation ID,
 * allowing developers to trace the complete request from start to finish.
 */

